spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: test
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "test";
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/master.xml
    default-schema: test
    enabled: true
  application:
    name: Uchebnii proect